name: solar_controller
description: Solar Controller Mobile App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Google Sign In
  google_sign_in: ^6.1.5
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # MQTT
  mqtt_client: ^10.0.0
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # UI Components
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/